 version: 0.2

 phases:
   install:
     runtime-versions:
      docker: 18 
   build:
    commands:
      - java -version
      - echo Build started on `date`
      - echo Building the Docker image... 
 artifacts:
    files: 
      - appspec.yml
      - imagedefinitions.json	
